# Generated by Django 4.2.2 on 2023-07-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chet',
            name='Itogo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chet',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chet',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cofe',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cold_drinks',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tabels',
            name='chet',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tabels',
            name='count_of_guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tabels',
            name='num_of_table',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
