# Generated by Django 4.2.2 on 2023-07-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_chet_itogo_chet_count_chet_price_cofe_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chet',
            new_name='Check',
        ),
    ]
